#lang racket
(require "mlish-tests.rkt")
(require "mlish/queens.mlish")
(require "mlish/listpats.mlish")

;; (require "mlish/trees.mlish")
;; (require "mlish/chameneos.mlish")
;; (require "mlish/ack.mlish")
;; (require "mlish/ary.mlish")
;; (require "mlish/fannkuch.mlish")
;; (require "mlish/fasta.mlish")
;; (require "mlish/fibo.mlish")
;; (require "mlish/hash.mlish")
;; ;(require "mlish/heapsort.mlish")
;; (require "mlish/knuc.mlish")
;; (require "mlish/matrix.mlish")
;; (require "mlish/nbody.mlish")
